#!/usr/bin/env bash

set -e

script_name='deploy-sevm-worker'
install_root="${HOME}/install/sevm-tools"
keyfile="${HOME}/install/geth-accounts/accounts.txt"
deploy_root="${HOME}/deploy/sevm"
prepare_root="${HOME}/prepare/sevm"


# Utility functions - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

fatal() {
	local msg="$1" ; shift

	exec >&2

	echo "${script_name}: ${msg}"
	echo
	echo "Usage: $0 prepare                                                (1)"
	echo "       $0 generate <behaviors>                                   (2)"
	echo
	echo "Prepare the SEVM running directory in (1) or use the SEVM"
	echo "toolchain to generate a network from a list of machines with the"
	echo "corresponding numbers of nodes <behaviors>"

	exit 1
}

setup_environment() {
	if [ ! -e "${install_root}" ] ; then
	fatal "cannot find sevm-tools install at '${install_root}'"
	fi

	if [ ! -f "${keyfile}" ] ; then
	fatal "cannot find geth accounts list at '${keyfile}'"
    fi

	# if [ ! -f "$HOME/helper" ]; then
	# 	echo "Cannot find helper script" >&2
	# 	exit 1
	# fi
	# . "$HOME/helper"
}

list_blockchain_nodes() {
	if [ $# -lt 1 ] ; then
	fatal "missing behaviors operand"
	elif [ $# -gt 1 ] ; then
	fatal "unexpected operand '$2'"
	fi

	local behaviors="$1" ; shift
    local line ip count

    while read line ; do
	ip="$(echo "${line}" | cut -d':' -f1)"
	count="$(echo "${line}" | cut -d':' -f2)"

	while [ ${count} -gt 0 ] ; do
	    echo "${ip}"
	    count=$(( count - 1 ))
	done
    done < "${behaviors}"
}


# Prepare action  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

prepare() {
	if [ $# -gt 0 ] ; then
	fatal "unexpected operand '$1'"
	fi

	if [ -e "${deploy_root}" ] ; then
	rm -rf "${deploy_root}"
	fi

	mkdir -p "${deploy_root}"

	if [ ! -d "${prepare_root}" ] ; then
	mkdir -p "${prepare_root}"
	fi
}


# Generate action - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

generate() {
	if [ $# -lt 1 ] ; then
	fatal "missing behaviors operand"
	elif [ $# -gt 1 ] ; then
	fatal "unexpected operand '$2'"
	fi

	local behaviors="${HOME}/$1" ; shift
	local netroot="${deploy_root}/network"

	setup_environment

	if [ -e "${netroot}" ] ; then
	rm -rf "${netroot}"
	fi

	local numnode=$(list_blockchain_nodes "${behaviors}" | wc -l)
	local numaccounts=10000
	local prepared_path="${prepare_root}/network-${numnode}-${numaccounts}"

	pushd "${install_root}"

	export PATH="${PWD}/node_modules/.bin:${PATH}"

	npx ts-node scripts/mygenesis.ts "${prepared_path}" "${behaviors}" "${keyfile}"

	popd

	cp -R "${prepared_path}" "${netroot}"

	tar -C "${deploy_root}" -czf "${netroot}.tar.gz" 'network'

	rm -rf "${netroot}"
}


# Main script - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ $# -lt 1 ] ; then
	fatal "missing action operand"
fi

action="$1" ; shift

case "${action}" in
	'prepare')
	prepare "$@"
	;;
	'generate')
	generate "$@"
	;;
	*)
	fatal "unknown action: '${action}'"
	;;
esac
