#!/bin/bash
#
#   install-algorand - install the Algorand blockchain from its repository
#

set -e

rust_version='1.52.1'
rust_url="https://static.rust-lang.org/dist/rust-${rust_version}-$(uname -m)-unknown-linux-gnu.tar.gz"

libra_url='https://github.com/diem/diem.git'
libra_checkout='testnet'

if ! command -v 'sudo' > '/dev/null' ; then
    echo "Cannot find command 'sudo'" >&2
    exit 1
fi

sudo -n apt-get -o DPkg::Lock::Timeout=1200 install -yy 'clang' 'cmake' 'gcc' 'git' 'libssl-dev' 'make' \
     'pkg-config'
curl -L "${rust_url}" | tar --one-top-level="install/rust${rust_version}install" --strip-components=1 -xzf -
."/install/rust${rust_version}install/install.sh" --destdir="install/rust${rust_version}" --prefix='' --without=rust-docs --disable-ldconfig
export PATH="${PWD}/install/rust${rust_version}/bin:${PATH}"

# Create an install dir if not already there.
#
if [ ! -e 'install' ] ; then
    mkdir 'install'
fi

if [ -e 'install/libra' ] ; then
    sudo rm -rf 'install/libra'
fi

# Clone Libra from the official repository and build it.
#
git clone "${libra_url}" 'install/libra'
(
    cd 'install/libra'

    git checkout "${libra_checkout}"

    export RUSTFLAGS="-Ctarget-cpu=native -Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3"
    export CARGO_PROFILE_RELEASE_LTO=thin

    # I don't know why but the compilation sometimes fails midway for no
    # reason (although I suspect it's because of out-of-memory).
    # Restart the compilation a couple of times until it compiles.
    #
    for try in $(seq 1 10) ; do
	if cargo build --release \
		 -p diem-node \
		 -p diem-swarm \
		 -p cli
	then
	    break
	fi
    done
)
